config/routes.rb
Rails.application.routes.draw do
  resources :pages
  root 'home#index'
  resources :products
  resources :products
  devise_for :users
  devise_for :admins, controllers: { registrations: "registrations"}
  mount Piggybak::Engine => '/checkout', as: :piggybak
  mount PiggybakTaxonomy::Engine => '/', :as => 'piggybak_taxonomy'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:#
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/image.rb
class Image < ActiveRecord::Base
  has_attached_file :asset,
    :styles => {
      :thumb => "50x50#",
      :medium => "200x200", 
      :large => "400x400"}
  validates_attachment_content_type :asset, :content_type => /\Aimage\/.*\Z/
  # add a delete_<asset_name> method:
  # attr_accessor :delete_asset
  # before_validation { self.asset.clear if self.delete_asset == '1' }
  # has_and_belongs_to_many :products
end

app/models/page.rb
class Page < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base
  acts_as_sellable_with_variants
  has_many :images
  scope :mens, -> { where(mens:true) }
  scope :womens, -> { where(mens:false) }
  # scope :search, -> { where(mens:true) }
  scope :gender, -> (gender) { where mens: gender == 'true' }
  # scope :size, -> (size) { where status: status }
  # scope :location, -> (location_id) { where location_id: location_id }
  # scope :starts_with, -> (name) { where("name like ?", "#{name}%")}
end

app/models/search_engine_optimization.rb
class SearchEngineOptimization < ActiveRecord::Base
end

app/models/slide.rb
class Slide < ActiveRecord::Base
  has_attached_file :image
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  # def body
  #   attributes[:body].html_safe
  # end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  acts_as_orderer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :init_variables?
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def init_variables?
    @nav = Page.all
    @meta = SearchEngineOptimization.all
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    # @products = Product.all
    @slides = Slide.all
    @recent = Product.last(5).reverse
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page, only: [:show]

  # GET /pages
  # GET /pages.json
  def index
    @pages = Page.all
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page
      @page = Page.find(params[:id])
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show]

  # GET /products
  # GET /products.json


  def index
    @products = Product.all
    @products = @products.gender(params[:gender]) if params[:gender].present?
  end

  # GET /products/1
  # GET /products/1.json
  # def show

  def options_for_klass(klass)
    options = ::PiggybakVariants::OptionConfiguration.where(klass: klass).includes(:option).collect { |oc| oc.option }
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_action :one_admin_registered?

  protected
  def one_admin_registered?
    if ((Admin.count == 1) & (admin_signed_in?))
      redirect_to root_path
    elsif Admin.count == 1
      redirect_to new_admin_session_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
  def get_price_range(product)
    # puts product
    # <script>
    #   var variant_map = <%= raw(variant_map_local(product)) %>;
    #   console.log(variant_map);
    #   var lowest = 0;
    #   var highest = 0;
    #   for(var key in variant_map) {
    #     var price = variant_map[key].raw_price;
    #     console.log(price+' - '+lowest+'/'+highest);
    #     if((!lowest) || (price < lowest)) lowest = price;
    #     if((!highest) || (price > highest)) { highest = price; }
    #   }
    # </script>
    lowest=nil;
    highest=nil;
    map = variant_map_local(product);
    map.each do |key, value|
      price = map[key][:raw_price]
      if((!lowest) or (price < lowest))
        lowest = price
      end
      if((!highest) or (price > highest))
        highest = price
      end
    end

    return "$"+lowest.to_s + ((lowest == highest)? "" : " - $"+highest.to_s);
  end
  def variant_map_local(object)
    map = {}
    object.variants.includes(:piggybak_sellable).available.each do |variant|
      map[variant.option_values.hash_ordered.map { |ov| ov.id }.join('_')] = {
        :id => variant.piggybak_sellable.id,
        :price => number_to_currency(variant.piggybak_sellable.price),
        :raw_price => variant.piggybak_sellable.price
      }
    end
    return map
  end
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/home/index.html.erb
<script>
  $(function (){
    var $images = $('.slider-image');
    var iteration = 0;
    $images.detach();
    var update = function(){
      var speed = 300;
      $('.slider-body').fadeOut(speed, function(){
        $('.slider-body').html($images[iteration]);
        $('.slider-body').fadeIn(speed);
      });
    }
    var next = function(){ if(++iteration > $images.length-1) iteration = 0; update(); }
    $('#slider > i:first-of-type').on('click',function(){ if(--iteration < 0) iteration = $images.length-1; update(); });
    $('#slider > i:last-of-type').on('click',next);
    update();
    if($images.length > 1) setInterval(next,8000);
  });
</script>
<section id='slider'>
  <i class="fa fa-angle-left"></i>
    <div class='slider-body'>
      <% @slides.each do |slide| %>
        <!-- <img src="<%= slide.image%>"> -->
        <div class='slider-image' style='background-image:linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5) ),url("<%= slide.image %>")'>
          <div class='slider-content'>
            <div class='slider-text-content'>
            <h1><%= slide.header %></h1>
            <h1><%= slide.sub_header %></h1>
            <p><%= raw(slide.body) %></p>
            <%= link_to(slide.button_name, slide.url) %>
          </div>
          </div>
          <!-- <a href="<%= slide.url %>"><button><%= slide.button_name %></button> -->
        </div>
      <% end %>
    </div>
  <i class="fa fa-angle-right"></i>
</section>

  <section id='products'>
    <hr class="split">
    <h1>New Products</h1>
    <!-- <div> -->
    <% @recent.each do |product| %>
      <%= render partial: "products/small", locals: {product:product} %>
      <!-- <hr> -->
    <% end %>
  <!-- </div> -->
  </section>
<section id='content'>
  <section id="social-content">
    <!-- <div id="facebook">
      <div class="fb-page" data-href="https://www.facebook.com/prolevelwear" data-tabs="timeline" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"><div class="fb-xfbml-parse-ignore"><blockquote cite="https://www.facebook.com/prolevelwear"><a href="https://www.facebook.com/prolevelwear">Prolevel Professional Gaming Wear</a></blockquote></div></div>
    </div> -->
    <div id="twitter">
      <a class="twitter-timeline" href="https://twitter.com/prolevelwear" data-widget-id="684914629026291712" data-chrome="transparent noscrollbar ">Tweets by @prolevelwear</a>
    </div>
  </section>
</section>
<!-- Twitter Shit -->
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <title>ProLevelWear | Professional Gaming wear</title>
  <% @meta.each do |tag| %> <meta name="<%= tag.name %>" content="<%= tag.content %>"> <% end %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script type="text/javascript" src="https://js.stripe.com/v1/"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</head>
<body>
  <img src='<%= image_path("logo.png") %>' id='logo'>
  <header>
    <section class="mobile-menu">
      <a id="nav-toggle" href="#"><span></span></a>
    </section>
    <section class="mobile-menu-wrapper">
        <nav class="mobile">
          <ul>
            <li><%= link_to "<span>Prolevel Gaming</span>".html_safe, main_app.root_url %></li>
            <li><%= link_to "<span>Products</span>".html_safe, main_app.products_url %></li>
            <% @nav.each do |page| %>
              <li><%= link_to "<span>#{page.title}</span>".html_safe, Rails.application.routes.url_helpers.page_path(page) %></li>
            <% end %>
            <li>
              <% cart = Piggybak::Cart.new(request.cookies["cart"]) %>
              <a href="<%= piggybak.cart_url %>"><span><i class='fa fa-shopping-cart'></i> Cart <%= number_to_currency(cart.total) %></span></a>
            </li>
        </ul>
        </nav>
    </section>

    <nav>
      <ul id="top-level">
        <li><%= link_to "<span>Prolevel Gaming</span>".html_safe, main_app.root_url %></li>
        <li class="products-drop"><%= link_to "<span>Products</span>".html_safe, main_app.products_url %><ul class="sub-level">
            <li><%= link_to "<span>NEW</span>".html_safe, main_app.products_url %></li>
            <li><%= link_to "<span>Hoodies</span>".html_safe, main_app.products_url(:gender => "true") %></li>
            <li><%= link_to "<span>Performance Shirts</span>".html_safe, main_app.products_url(:gender => "false") %></li>
            <li><%= link_to "<span>Jersey</span>".html_safe, main_app.products_url %></li>
            <li><%= link_to "<span>Head Gear</span>".html_safe, main_app.products_url %></li>
          </ul>
        </li>
        <% @nav.each do |page| %>
          <li><%= link_to "<span>#{page.title}</span>".html_safe, Rails.application.routes.url_helpers.page_path(page) %></li>
        <% end %>
        <% if user_signed_in? %>
          <li><%= link_to("<span>Logout</span>".html_safe, main_app.destroy_user_session_path, :method => :delete) %>  </li>
        <% else %>
          <li><%= link_to "<span>Login</span>".html_safe, main_app.new_user_session_path %></li>
        <% end %>
        <li>
          <% cart = Piggybak::Cart.new(request.cookies["cart"]) %>
          <a href="<%= piggybak.cart_url %>"><span><i class='fa fa-shopping-cart'></i> Cart <%= number_to_currency(cart.total) %></span></a>
        </li>
      </ul>
    </nav>

  </header>
  <!-- <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p> -->
  <main>
    <%= yield %>

  </main>
      <footer>
        <div class="footer">
          <section>
            <h3>CONNECT WITH US:</h3>
            <a href="tel:5595454534">559-545-4534</a><br/>
            <a href="https://www.facebook.com/prolevelwear"><i class="fa fa-2x fa-facebook"></i></a>
            <a href="https://www.twitter.com/prolevelwear"><i class="fa fa-2x fa-twitter"></i></a>
          </section>
        </div>
        <% if !admin_signed_in? %>
          <%= link_to 'Login as Admin', main_app.new_admin_session_path %>
        <% else %>
          <%= link_to 'Admin Panel', rails_admin.dashboard_path %>
        <% end %>
      </footer>

</body>
<!-- Facebook Shit -->
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.5&appId=748936895238713";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<script>
  $(function(){$('#nav-toggle').click(function(){
    $('#nav-toggle').toggleClass('active');
    $('.mobile').toggleClass('drawer');
    $('#logo').toggleClass('drawer');
  })});
</script>
</html>

app/views/pages/show.html.erb
<div id="custom-pages">
  <section>
    <div class="inner-header">
      <h1><%= @page.header %></h1>
    </div>
  <div class="inner-body"><%= @page.content.html_safe %></div>
</section>
</div>

app/views/products/_form.html.erb
<script type="text/javascript">
  $(function() {

    var piggybak_variants = {
    	refreshControls : function(data) {
        // console.log(variant_map);
    		if(data.all_selected) { // if all selected
          // console.log(data.selected.reverse());
    			var selected_key = data.selected.reverse().join('_');
          // console.log("selected_key: "+selected_key);
          // console.log(variant_map[selected_key]);
    			if(variant_map[selected_key]) {
            // console.log("Ayy lmao");
    				$('.variant_options form').show();
    				$('#sellable_id').val(variant_map[selected_key].id);
    				$('#variant_price span').html(variant_map[selected_key].price);
    			} else { // if variant not available
    				$('.variant_options form').hide();
    				$('.unavailable').show();
    			}
    		} else { // if not all selected
    			$('.all_selected').show();
    			$('.variant_options form').hide();
    		}
    	},
    	extractDropdownValues: function() {
    		var all_selected = true;
    		// TODO: Nice to see if easier way to select by value, but select[value=""] doesn't work
    		$('.variant_options select').each(function() {
    			if ($(this).val() == '') {
    				all_selected = false;
    			}
    		});
    		if(!all_selected) {
    			return { all_selected: false, selected: '' };
    		}

    		var selected = new Array();
    		$.each($('.variant_options .option select'), function(i, j) {
    			selected.push($(this).val());
    		});
    		return { all_selected: true, selected: selected};
    	},
    	toggleVariantForm: function() {
    		$('.unavailable, .all_selected').hide();
    		var data;
    		if ($('.variant_options input[type=radio]').length > 0){
    			data = piggybak_variants.extractRadioButtonValues();
    		} else {
    			data = piggybak_variants.extractDropdownValues();
    		};
    		piggybak_variants.refreshControls(data);
    	}
    }

    var variant_map = <%= raw variant_map(@product) %>;
    $('.variant_options select').change(function() { piggybak_variants.toggleVariantForm(); });
    $('.variant_options input[type=radio]').click(function() { piggybak_variants.toggleVariantForm(); });
    if($('.variant_options').size() > 0) {
      piggybak_variants.toggleVariantForm();
    }
  });
</script>

<div class="variant_options">
	<% options_for_klass(@product.class).each do |option| -%>
	<div class="option" id="option_<%= option.id %>">
		<h4><%= option.name %></h4>
		<%= select_tag option.name, options_for_select(option.option_values.map{ |o| [o.name, o.id] }), include_blank: false %>
		<br />
	</div>
	<% end -%>
	<span class="all_selected">You must select a choice from each option.</span>
	<span class="unavailable">This combination is not available.</span>
	<%= form_tag piggybak.cart_add_url do -%>
		<input type="hidden" id="sellable_id" name="sellable_id" />
		<div id="variant_price">Price: <span></span></div>
		<label for="quantity">Quantity</label>
		<%= number_field_tag :quantity, 1 %>
		<%= submit_tag "Add to Cart", :id => "submit" %>
	<% end -%>
</div>

app/views/products/_list.html.erb
<div class='product'>
  <div class="product-image"><%= image_tag product.images[0].asset(:medium) %></div>
  <div class='product-information'>
    <h1><%= product.name %></h1>
    <span><%= get_price_range(product) %></span>
    <!-- <div class='inner-description'>
      <%= raw(product.description) %>
    </div> -->
    <a href="<%= product_path(product) %>" class='fancy-button'>Buy</a>
  </div>
  <!-- <br/> -->
  <!-- <div class="fb-like" data-href="https://developers.facebook.com/docs/plugins/" data-layout="button" data-action="like" data-show-faces="true" data-share="true"></div> -->
  <!-- <br/> -->
  <!-- <div id='inner-description'>
    <%= raw(product.description) %>
  </div> -->
</div>

app/views/products/_small.html.erb
<a href="<%= product_path(product) %>">
  <article class="product">
    <div class="product-image">
      <%= image_tag product.images[0].asset(:medium) %>
    </div>
    <div class="product-info">
      <h1><%= product.name %></h1>
      <span><%= get_price_range(product) %></span>
      <!-- <span class='fancy-button'>Buy</span> -->
    </div>
  </article>
</a>

<!-- <script>
  var variant_map = <%= raw(variant_map_local(product)) %>;
  console.log(variant_map);
  var lowest = 0;
  var highest = 0;
  for(var key in variant_map) {
    var price = variant_map[key].raw_price;
    console.log(price+' - '+lowest+'/'+highest);
    if((!lowest) || (price < lowest)) lowest = price;
    if((!highest) || (price > highest)) { highest = price; }
  }
</script> -->

app/views/products/index.html.erb
<section id="product-list">
  <% @products.each do |product| %>
    <%= render partial: "products/list", locals: {product:product} %>
  <% end %>
</section> 
<style> main { display:flex; flex-direction:column; } </style>

app/views/products/show.html.erb
<section id='product-info'>
  <section id='product-image'>
    <div id='csssucks'>
      <aside id='image-selector'>
        <% @product.images.each do |image| %>
          <img src="<%= image.asset(:thumb) %>" data-full="<%= image.asset %>">
        <% end %>
      </aside>
    </div>
    <img id="selected-image" src="<%= @product.images[0].asset %>>">
  </section>
  <div id='product-description'>
    <h1><%= @product.name %></h1>
    <div class="fb-like" data-href="https://developers.facebook.com/docs/plugins/" data-layout="button" data-action="like" data-show-faces="true" data-share="true"></div>
    <br/>
    <!-- <br/> -->
    <div id='inner-description'>
      <%= raw(@product.description) %>
    </div>
    <span><%= get_price_range(@product) %></span>
  </div>
</section>
<%= render "products/form", locals:{product:@product} %>
<script>
  $(function(){
    $selector = $('#image-selector');
    $selected = $('#selected-image');
    $selector.on('click',function(e){
      $selected.attr('src', $(e.target).attr('data-full'));
      $selected.attr('data-magnify-src', $(e.target).attr('data-full'));
      $selected.magnify();
    });
    // $selected.load();
  });
</script>